### ISSUE TITLE
Cannot read property 'dryRun' of undefined

### ISSUE THREAD

**Issue by tuffant21** [fiznool/express-mongo-sanitize#87]
Hi guys, I am getting this error every time mongo sanitize is hit. Any ideas what is causing it?

Error:
```
TypeError: Cannot read property 'dryRun' of undefined
   at _sanitize (/var/www/server/node_modules/express-mongo-sanitize/index.js:43:32)
   at Function.sanitize (/var/www/server/node_modules/express-mongo-sanitize/index.js:91:10)
   at Socket.<anonymous> (/var/www/server/src/config/middleware.js:43:38)
   at ZoneDelegate.invokeTask (/var/www/server/src/public/server/main.js:1:1679210)
   at Zone.runTask (/var/www/server/src/public/server/main.js:1:1672220)
   at invokeTask (/var/www/server/src/public/server/main.js:1:1680657)
   at Socket.ZoneTask.options.useG.invoke (/var/www/server/src/public/server/main.js:1:1680504)
   at Socket.emit (events.js:315:20)
   at Socket.EventEmitter.emit (domain.js:467:12)
   at Socket.emitUntyped (/var/www/server/node_modules/socket.io/dist/typed-events.js:69:22)
   at /var/www/server/node_modules/socket.io/dist/socket.js:428:39
   at ZoneDelegate.invokeTask (/var/www/server/src/public/server/main.js:1:1679210)
   at Zone.runTask (/var/www/server/src/public/server/main.js:1:1672220)
   at invokeTask (/var/www/server/src/public/server/main.js:1:1680657)
   at ZoneTask.options.useG.invoke (/var/www/server/src/public/server/main.js:1:1680504)
   at data.args.<computed> (/var/www/server/src/public/server/main.js:1:1717826)
```

Node v14.16.1
express-mongo-sanitize v2.1.0

Here is my set up.
```
const mongoSanitize = require('express-mongo-sanitize');
router.use(mongoSanitize());
```

Got it figured out. If you don't pass in an object for options, it throws that error. Will create a PR with a fix.

**Comment by fiznool** [comment]
Closed via #88
